-- PostgreSQL + pgvector production schema. SQLite demo uses the same logical entities.
CREATE EXTENSION IF NOT EXISTS vector;
CREATE TABLE IF NOT EXISTS sources (source_id TEXT PRIMARY KEY, name TEXT NOT NULL, url TEXT, version TEXT, license TEXT NOT NULL, commercial_status TEXT NOT NULL, retrieved_at DATE NOT NULL, checksum TEXT, raw_location TEXT);
CREATE TABLE IF NOT EXISTS evidence (evidence_id TEXT PRIMARY KEY, source_id TEXT NOT NULL REFERENCES sources(source_id), source_record_id TEXT, evidence_type TEXT NOT NULL CHECK (evidence_type IN ('FACT','SOURCE_DERIVED','INFERENCE','MODEL_PREDICTION','HYPOTHESIS','EXPERIMENTALLY_VALIDATED')), confidence REAL CHECK (confidence >= 0 AND confidence <= 1), retrieved_at DATE NOT NULL, derivation_json JSONB);
CREATE TABLE IF NOT EXISTS ingredients (ingredient_id TEXT PRIMARY KEY, canonical_name TEXT NOT NULL, scientific_name TEXT, category TEXT, family TEXT, cuisine TEXT, source_evidence_id TEXT REFERENCES evidence(evidence_id));
CREATE TABLE IF NOT EXISTS ingredient_aliases (alias_id TEXT PRIMARY KEY, ingredient_id TEXT REFERENCES ingredients(ingredient_id), raw_value TEXT NOT NULL, normalized_value TEXT NOT NULL, language TEXT, transliteration TEXT, resolution_method TEXT, confidence REAL, source_evidence_id TEXT REFERENCES evidence(evidence_id));
CREATE TABLE IF NOT EXISTS ingredient_states (state_id TEXT PRIMARY KEY, ingredient_id TEXT REFERENCES ingredients(ingredient_id), state_name TEXT NOT NULL, preparation_method TEXT, freshness TEXT, parent_state_id TEXT REFERENCES ingredient_states(state_id));
CREATE TABLE IF NOT EXISTS compounds (compound_id TEXT PRIMARY KEY, name TEXT NOT NULL, formula TEXT, molecular_weight REAL, smiles TEXT, inchikey TEXT, chemical_class TEXT);
CREATE TABLE IF NOT EXISTS ingredient_compounds (ingredient_id TEXT REFERENCES ingredients(ingredient_id), state_id TEXT REFERENCES ingredient_states(state_id), compound_id TEXT REFERENCES compounds(compound_id), occurrence REAL, basis TEXT, method TEXT, source_evidence_id TEXT REFERENCES evidence(evidence_id), PRIMARY KEY(ingredient_id,state_id,compound_id,source_evidence_id));
CREATE TABLE IF NOT EXISTS sensory_descriptors (descriptor_id TEXT PRIMARY KEY, modality TEXT NOT NULL CHECK(modality IN ('taste','odor','texture','physical')), name TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS ingredient_sensory (ingredient_id TEXT REFERENCES ingredients(ingredient_id), state_id TEXT REFERENCES ingredient_states(state_id), descriptor_id TEXT REFERENCES sensory_descriptors(descriptor_id), value REAL, scale TEXT, context TEXT, source_evidence_id TEXT REFERENCES evidence(evidence_id), PRIMARY KEY(ingredient_id,state_id,descriptor_id,source_evidence_id));
CREATE TABLE IF NOT EXISTS recipes (recipe_id TEXT PRIMARY KEY, title TEXT NOT NULL, cuisine TEXT, region TEXT, source_id TEXT REFERENCES sources(source_id), source_record_id TEXT, canonical_recipe_group TEXT, duplicate_status TEXT);
CREATE TABLE IF NOT EXISTS recipe_ingredients (recipe_id TEXT REFERENCES recipes(recipe_id), ordinal INTEGER, raw_value TEXT NOT NULL, ingredient_id TEXT REFERENCES ingredients(ingredient_id), state_id TEXT REFERENCES ingredient_states(state_id), quantity REAL, unit TEXT, resolution_method TEXT, confidence REAL, PRIMARY KEY(recipe_id,ordinal));
CREATE TABLE IF NOT EXISTS processes (process_id TEXT PRIMARY KEY, name TEXT UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS recipe_steps (recipe_id TEXT REFERENCES recipes(recipe_id), step_id INTEGER, ordinal INTEGER, raw_text TEXT NOT NULL, process_id TEXT REFERENCES processes(process_id), temperature REAL, temperature_unit TEXT, duration REAL, duration_unit TEXT, medium TEXT, water_condition TEXT, fat_condition TEXT, expected_transformation TEXT, resulting_state TEXT, source_evidence_id TEXT REFERENCES evidence(evidence_id), PRIMARY KEY(recipe_id,step_id));
CREATE TABLE IF NOT EXISTS transformations (transformation_id TEXT PRIMARY KEY, input_state_id TEXT, process_id TEXT REFERENCES processes(process_id), output_state_id TEXT, parameters_json JSONB, affected_dimensions_json JSONB, evidence_id TEXT REFERENCES evidence(evidence_id));
CREATE TABLE IF NOT EXISTS edges (edge_id TEXT PRIMARY KEY, subject_id TEXT NOT NULL, predicate TEXT NOT NULL, object_id TEXT NOT NULL, frequency REAL, calculation_method TEXT, evidence_id TEXT REFERENCES evidence(evidence_id));
CREATE TABLE IF NOT EXISTS embeddings (entity_id TEXT NOT NULL, representation_type TEXT NOT NULL, model TEXT NOT NULL, version TEXT NOT NULL, vector vector, metadata JSONB, PRIMARY KEY(entity_id,representation_type,model,version));
CREATE TABLE IF NOT EXISTS experiments (experiment_id TEXT PRIMARY KEY, hypothesis TEXT NOT NULL, protocol TEXT, dataset_version TEXT, code_version TEXT, configuration_json JSONB, created_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS predictions (prediction_id TEXT PRIMARY KEY, experiment_id TEXT REFERENCES experiments(experiment_id), entity_id TEXT, target TEXT, value_json JSONB, evidence_type TEXT, confidence REAL);

-- Representation-layer extensions: modality-specific and evidence-preserving.
ALTER TABLE evidence ADD COLUMN IF NOT EXISTS data_status TEXT CHECK (data_status IN ('REAL','SYNTHETIC','MODEL_DERIVED','HYPOTHETICAL')) DEFAULT 'REAL';
ALTER TABLE compounds ADD COLUMN IF NOT EXISTS synonyms_json JSONB;
ALTER TABLE compounds ADD COLUMN IF NOT EXISTS chemical_classes_json JSONB;
ALTER TABLE ingredient_compounds ADD COLUMN IF NOT EXISTS presence BOOLEAN;
ALTER TABLE ingredient_compounds ADD COLUMN IF NOT EXISTS concentration_unit TEXT;
ALTER TABLE ingredient_compounds ADD COLUMN IF NOT EXISTS concentration_statistic TEXT;
ALTER TABLE ingredient_compounds ADD COLUMN IF NOT EXISTS matrix TEXT;
CREATE TABLE IF NOT EXISTS sensory_observations (observation_id TEXT PRIMARY KEY, ingredient_id TEXT, state_id TEXT, modality TEXT NOT NULL CHECK(modality IN ('taste','odor','texture','physical')), descriptor TEXT NOT NULL, value_json JSONB, observed BOOLEAN NOT NULL, measurement_method TEXT, context TEXT, evidence_id TEXT REFERENCES evidence(evidence_id));
CREATE TABLE IF NOT EXISTS odor_thresholds (threshold_id TEXT PRIMARY KEY, compound_id TEXT REFERENCES compounds(compound_id), value REAL, unit TEXT, medium TEXT, temperature REAL, temperature_unit TEXT, measurement_method TEXT, evidence_id TEXT REFERENCES evidence(evidence_id));
CREATE TABLE IF NOT EXISTS evidence_conflicts (conflict_id TEXT PRIMARY KEY, assertion_key TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('agreement','conflict','uncertain')), preferred_evidence_id TEXT, rationale TEXT);
CREATE TABLE IF NOT EXISTS representations (entity_id TEXT NOT NULL, representation_type TEXT NOT NULL, model TEXT NOT NULL, version TEXT NOT NULL, vector_json JSONB, observed_mask_json JSONB, source_features_json JSONB, data_status TEXT NOT NULL, evidence_id TEXT REFERENCES evidence(evidence_id), created_at TIMESTAMP NOT NULL, PRIMARY KEY(entity_id,representation_type,model,version));
CREATE TABLE IF NOT EXISTS transformation_observations (transformation_id TEXT REFERENCES transformations(transformation_id), output_dimension TEXT NOT NULL, value_json JSONB, evidence_id TEXT REFERENCES evidence(evidence_id), PRIMARY KEY(transformation_id,output_dimension,evidence_id));
